// <auto-generated />
namespace E_Commerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201906201109139_firstcreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
